services:
    admin.event_category:
        class: App\Admin\EventCategoryAdmin
        arguments: [~, App\Entity\EventCategory, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'admin.with.category', group: 'admin.with.event' }
    admin.event_location:
        class: App\Admin\EventLocationAdmin
        arguments: [~, App\Entity\EventLocation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'admin.with.location', group: 'admin.with.event' }
    admin.event_collaborator:
        class: App\Admin\EventCollaboratorAdmin
        arguments: [~, App\Entity\EventCollaborator, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'admin.with.collaborator', group: 'admin.with.event' }
    admin.event_activity:
        class: App\Admin\EventActivityAdmin
        arguments: [~, App\Entity\EventActivity, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'admin.with.activity', group: 'admin.with.event' }
