services:
    admin.event_category:
        class: App\Admin\EventCategoryAdmin
        arguments: [~, App\Entity\EventCategory, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Categories', group: 'Events' }
    admin.event_location:
        class: App\Admin\EventLocationAdmin
        arguments: [~, App\Entity\EventLocation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Ubicacions', group: 'Events' }
    admin.event_collaborator:
        class: App\Admin\EventCollaboratorAdmin
        arguments: [~, App\Entity\EventCollaborator, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Col·laboradors', group: 'Events' }
