services:
    admin.event_category:
        class: App\Admin\EventCategoryAdmin
        arguments: [~, App\Entity\EventCategory, ~, '@sonata.admin.entity_manager', '@vich_uploader.templating.helper.uploader_helper', '@liip_imagine.cache.manager']
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'admin.with.category', group: 'admin.with.event' }
    admin.event_location:
        class: App\Admin\EventLocationAdmin
        arguments: [~, App\Entity\EventLocation, ~, '@sonata.admin.entity_manager', '@vich_uploader.templating.helper.uploader_helper', '@liip_imagine.cache.manager']
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'admin.with.location', group: 'admin.with.event' }
    admin.event_collaborator:
        class: App\Admin\EventCollaboratorAdmin
        arguments: [~, App\Entity\EventCollaborator, ~, '@sonata.admin.entity_manager', '@vich_uploader.templating.helper.uploader_helper', '@liip_imagine.cache.manager']
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'admin.with.collaborator', group: 'admin.with.event' }
    admin.event_activity:
        class: App\Admin\EventActivityAdmin
        arguments: [~, App\Entity\EventActivity, ~, '@sonata.admin.entity_manager', '@vich_uploader.templating.helper.uploader_helper', '@liip_imagine.cache.manager']
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'admin.with.activity', group: 'admin.with.event' }
    admin.team_partner:
        class: App\Admin\TeamPartnerAdmin
        arguments: [~, App\Entity\TeamPartner, ~, '@sonata.admin.entity_manager', '@vich_uploader.templating.helper.uploader_helper', '@liip_imagine.cache.manager']
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'admin.with.team_partner', group: 'admin.with.team' }
    admin.configuration_user:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User, ~, '@fos_user.user_manager.default']
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'admin.with.user', group: 'admin.with.settings' }
