fos_user:
    db_driver:     orm
    firewall_name: admin
    user_class:    App\Entity\User
    group:
        group_class:   Sonata\UserBundle\Entity\BaseGroup
        group_manager: sonata.user.orm.group_manager
    service:
        mailer:       fos_user.mailer.noop
        user_manager: sonata.user.orm.user_manager
    from_email:
        address:     '%env(MAILER_SENDER_ADDRESS)%'
        sender_name: '%env(MAILER_SENDER_NAME)%'
