liip_imagine:
    driver: 'gd'
    loaders:
       default:
          filesystem:
            locator: filesystem_insecure
    filter_sets:
        2000xY:
            quality: 90
            filters:
                thumbnail:
                    size:          [2000, null]
                    mode:          outbound
                    allow_upscale: false
        800x600:
            quality: 90
            filters:
                thumbnail:
                    size:          [800, 600]
                    mode:          outbound
                    allow_upscale: false
        480x480:
            quality: 90
            filters:
                thumbnail:
                    size:          [480, 480]
                    mode:          outbound
                    allow_upscale: false
        480x480_BW:
            quality: 90
            filters:
                grayscale: ~
                thumbnail:
                    size:          [480, 480]
                    mode:          outbound
                    allow_upscale: false
        480x480_inset:
            quality: 90
            filters:
                thumbnail:
                    size:          [440, 440]
                    mode:          inset
                background:
                    color: '#FFFFFF'
                    size: [480, 480]
                    position: center
        480xY:
            quality: 90
            filters:
                thumbnail:
                    size:          [480, null]
                    mode:          outbound
                    allow_upscale: false
        360x360:
            quality: 100
            filters:
                thumbnail:
                    size:          [360, 360]
                    mode:          outbound
                    allow_upscale: false
        180x180:
            quality: 100
            filters:
                thumbnail:
                    size:          [180, 180]
                    mode:          outbound
                    allow_upscale: false
        70xY:
            quality: 100
            filters:
                thumbnail:
                    size:          [70, null]
                    mode:          outbound
                    allow_upscale: false
        60x60:
            quality: 100
            filters:
                thumbnail:
                    size:          [60, 60]
                    mode:          outbound
                    allow_upscale: false
        flip_x:
            jpeg_quality:          100
            png_compression_level: 8
            filters:
                strip: ~
                flip:
                    axis: x
        squared_thumbnail:
            jpeg_quality:          100
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [253, 253]
                    mode:          outbound
                    allow_upscale: true
                background:
                    size:     [256, 256]
                    position: center
                    color:    '#FFFFFF'
