liip_imagine:
    # "gd", "gmagick" or "imagick"
    driver: 'gd'
    filter_sets:
        2000xY:
            quality: 90
            filters:
                thumbnail:
                    size:          [2000, null]
                    mode:          outbound
                    allow_upscale: false
        480xY:
            quality: 90
            filters:
                thumbnail:
                    size:          [480, null]
                    mode:          outbound
                    allow_upscale: false
        70xY:
            quality: 100
            filters:
                thumbnail:
                    size:          [70, null]
                    mode:          outbound
                    allow_upscale: false
        flip_x:
            jpeg_quality:          98
            png_compression_level: 8
            filters:
                strip: ~
                flip:
                    axis: x
        squared_thumbnail:
            jpeg_quality:          98
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [253, 253]
                    mode:          outbound
                    allow_upscale: true
                background:
                    size:     [256, 256]
                    position: center
                    color:    '#FFF'
