security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    access_decision_manager:
        strategy: unanimous
    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_SONATA_ADMIN
            - ROLE_ADMIN_EVENT_CATEGORY_ALL
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            anonymous: true
            pattern:   ^/(ca|es|en)/admin(.*)
            context:   user
            form_login:
                provider:     fos_userbundle
                login_path:   /ca/admin/login
                use_forward:  false
                check_path:   /ca/admin/login_check
                failure_path: /ca/admin/login
            logout:
                path:   /ca/admin/logout
                target: /ca/admin/login
        main:
            anonymous: true
            pattern:   ^/(.*)
            context:   user
    access_control:
        # enabled private entry points
        - { path: ^/(ca|es|en)/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(ca|es|en)/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(ca|es|en)/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(ca|es|en)/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(ca|es|en)/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        # enabled public entry points
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
