security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    access_decision_manager:
        strategy: unanimous
    role_hierarchy:
        ROLE_CMS:
            - ROLE_USER
            - ROLE_SONATA_ADMIN
            - ROLE_ADMIN_EVENT_CATEGORY_ALL
            - ROLE_ADMIN_EVENT_LOCATION_ALL
            - ROLE_ADMIN_EVENT_COLLABORATOR_ALL
            - ROLE_ADMIN_EVENT_ACTIVITY_ALL
            - ROLE_ADMIN_TEAM_PARTNER_ALL
            - ROLE_ADMIN_TEAM_MEMBER_ALL
            - ROLE_ADMIN_BLOG_CATEGORY_ALL
            - ROLE_ADMIN_BLOG_POST_ALL
            - ROLE_ADMIN_CONTACT_MESSAGE_ALL
            - ROLE_ADMIN_CONTACT_NEWSLETTER_ALL
        ROLE_ADMIN:
            - ROLE_CMS
            - ROLE_ADMIN_CONFIGURATION_USER_ALL
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            anonymous: true
            pattern:   ^/(ca|es|en)/admin(.*)
            context:   user
            form_login:
                provider:                       fos_userbundle
                login_path:                     /ca/admin/login
                use_forward:                    false
                check_path:                     /ca/admin/login_check
                failure_path:                   /ca/admin/login
                default_target_path:            /ca/admin/dashboard
                always_use_default_target_path: true
                use_referer:                    true
            logout:
                path:   /ca/admin/logout
                target: /ca/admin/login
        main:
            anonymous: true
            pattern:   ^/(.*)
            context:   user
    access_control:
        # enabled private entry points
        - { path: ^/(ca|es|en)/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(ca|es|en)/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(ca|es|en)/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(ca|es|en)/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(ca|es|en)/admin/, role: [ROLE_CMS, ROLE_SONATA_ADMIN] }
        # enabled public entry points
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
