# Admin
sonata_admin:
    show_mosaic_button: false
    title_logo: 'build/vag_logo.png'
    options:
        html5_validate: true
        confirm_exit:   true
        use_select2:    true
        pager_links:    10
    persist_filters: true
    security:
        handler: sonata.admin.security.handler.role
    templates:
        layout: 'backend/base.html.twig'
        edit:   'backend/edit.html.twig'
    dashboard:
        groups:
            'admin.with.event':
                icon: "<i class='fa fa-calendar'></i>"
            'admin.with.settings':
                icon: "<i class='fa fa-cogs'></i>"
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

# Block
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
