stof_doctrine_extensions:
    default_locale: '%locale%'
    orm:
        default:
            sluggable:     true
            timestampable: true
            translatable:  true
            uploadable:    false
