twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        main_brand_title: 'VAG'
        main_brand_email: '%env(string:MAILER_SENDER_ADDRESS)%'
        admin_tag_version: 'v1.0.08'
        google_analytics_enabled: '%env(bool:GOOGLE_ANALYTICS_ENABLED)%'
        google_analytics_code: '%env(string:GOOGLE_ANALYTICS_CODE)%'
        google_maps_api_key: '%env(string:GOOGLE_MAPS_API_KEY)%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@SonataCore/Form/datepicker.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
