twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        main_brand_title: 'VAG'
        admin_tag_version: 'v1.0.03'
        google_analytics_enabled: '%env(bool:GOOGLE_ANALYTICS_ENABLED)%'
        google_analytics_code: '%env(string:GOOGLE_ANALYTICS_CODE)%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@SonataCore/Form/datepicker.html.twig'
