vich_uploader:
    db_driver: orm
    mappings:
        location:
            uri_prefix: '/uploads/locations'
            upload_destination: '%kernel.project_dir%/public/uploads/locations'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: {property: 'slug'}
        collaborator:
            uri_prefix: '/uploads/collaborators'
            upload_destination: '%kernel.project_dir%/public/uploads/collaborators'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: {property: 'slug'}
        activity:
            uri_prefix: '/uploads/activities'
            upload_destination: '%kernel.project_dir%/public/uploads/activities'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: {property: 'slug'}
