vich_uploader:
    db_driver: orm
    mappings:
        category:
            uri_prefix: '/uploads/categories'
            upload_destination: '%kernel.project_dir%/public/uploads/categories'
            namer:
                service: App\Naming\VichUploaderCustomNaming
                options: {property: 'slug'}
        location:
            uri_prefix: '/uploads/locations'
            upload_destination: '%kernel.project_dir%/public/uploads/locations'
            namer:
                service: App\Naming\VichUploaderCustomNaming
                options: {property: 'slug'}
        collaborator:
            uri_prefix: '/uploads/collaborators'
            upload_destination: '%kernel.project_dir%/public/uploads/collaborators'
            namer:
                service: App\Naming\VichUploaderCustomNaming
                options: {property: 'slug'}
        activity:
            uri_prefix: '/uploads/activities'
            upload_destination: '%kernel.project_dir%/public/uploads/activities'
            namer:
                service: App\Naming\VichUploaderCustomNaming
                options: {property: 'slug'}
        team:
            uri_prefix: '/uploads/team'
            upload_destination: '%kernel.project_dir%/public/uploads/team'
            namer:
                service: App\Naming\VichUploaderCustomNaming
                options: {property: 'slug'}
        partner:
            uri_prefix: '/uploads/partner'
            upload_destination: '%kernel.project_dir%/public/uploads/partner'
            namer:
                service: App\Naming\VichUploaderCustomNaming
                options: {property: 'slug'}
        blog:
            uri_prefix: '/uploads/blog'
            upload_destination: '%kernel.project_dir%/public/uploads/blog'
            namer:
                service: App\Naming\VichUploaderCustomNaming
                options: {property: 'slug'}
