# Imports
imports:
    - { resource: 'services/admin.yaml' }

# Parameters
parameters:
    locale: 'ca'
    app_array_locales: ['ca', 'es', 'en']
    app_locales: ca|es|en

# Services
services:
    _defaults:
        autowire:      true
        autoconfigure: true
        public:        false
        bind:
            $locales: '%app_locales%'
            $defaultLocale: '%locale%'
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Menu\FrontendMenu:
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
