- name: fix symfony logs directory apache ownership
  file:
    path: "{{ ansistrano_deploy_to }}/shared/var/logs"
    recurse: yes
    owner: "{{ remote_system_user }}"
    group: "{{ remote_system_group }}"
